import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";
import { NextPage } from "next";
import Link from "next/link";
import { useState } from "react";

export default function Home() {
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>Pharmacy App</title>
        <style>input::-ms-reveal, input::-ms-clear </style>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{sessionData?.user ? <HomePage /> : <SignInComponent />}</main>
    </>
  );
}

const SignInComponent = () => {
  return (
    <div className="relative mx-auto h-screen bg-gradient-to-br from-red-200 to-slate-300">
      <button
        className=" absolute left-1/2 top-1/2 rounded-md bg-blue-500 px-16 py-2 text-white"
        onClick={() => void signIn()}
      >
        Sign in
      </button>
    </div>
  );
};

const HomePage: NextPage = () => {
  const { data: sessionData } = useSession();
  return (
    <div className="bg-slate-200">
      <NavBar></NavBar>
      <h1>Dashboard</h1>
    </div>
  );
};

export const NavBar: NextPage = () => {
  const { data: sessionData } = useSession();
  return (
    <nav className="flex bg-white py-2 font-semibold text-blue-500">
      <Link href="/">
        <img src="/logo-default.png" className="h-12 w-16"></img>
      </Link>
      <div className="flex w-full justify-between">
        <ul className="mx-4 my-auto flex gap-8">
          <li className="group relative">
            <button className="">Danh mục</button>
            <div className="absolute top-0 mt-5 hidden text-slate-500 group-hover:block">
              <ul className="top-0 w-48 bg-white py-6 shadow">
                <li className="mb-2 mt-4">
                  <Link className="hover:text-blue-500" href="/lists/providers">
                    Danh mục nhà cung cấp
                  </Link>
                </li>
                <li>
                  <Link className="hover:text-blue-500" href="/lists/products">
                    Danh mục hàng hóa
                  </Link>
                </li>
              </ul>
            </div>
          </li>
          <li>Quản lý kho</li>
          <li>Xuất kho/bán hàng</li>
          <li>Báo cáo</li>
        </ul>
        <div className="mx-8 my-auto flex">
          <div className="group relative w-32">
            <button>{sessionData?.user.name}</button>
            <div className="absolute hidden h-auto group-hover:block">
              <ul className="top-0 w-48 bg-white py-6 shadow">
                <li>
                  <button>Đổi mật khẩu</button>
                </li>
                <li>
                  <button onClick={() => void signOut()}>Đăng xuất</button>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </nav>
  );
};
